#!/bin/sh

BACKUPDIR="/var/log"
BACKUPFILE="/conf/logsdata.tgz"
BACKUPOFF="<logsdatabackup>-1</logsdatabackup>"

if [ "$(grep -c "${BACKUPOFF}" /conf/config.xml)" != "0" ]; then
	rm -f ${BACKUPFILE}
elif [ "${1}" = "restore" ]; then
	if [ -f "${BACKUPFILE}" ]; then
		tar -C / -xzpf "${BACKUPFILE}"
	fi
else
	if [ -d "${BACKUPDIR}" ]; then
		tar -C / -czf "${BACKUPFILE}" ."${BACKUPDIR}"
	fi
fi
